{{- if and (.Values.clusterAutoscaler) (.Values.clusterAutoscaler.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.clusterAutoscaler.repoUrl }}
    path: {{ .Values.clusterAutoscaler.path }}
    targetRevision: {{ .Values.clusterAutoscaler.targetRevision }}
    helm:
      values: |
        {{- toYaml .Values.clusterAutoscaler.values | nindent 8 }}
      parameters:
      - name: awsRegion
        value: {{ .Values.region }}
      - name: rbac.serviceAccount.name
        value: {{ .Values.clusterAutoscaler.serviceAccountName }}
      - name: autoDiscovery.clusterName
        value: {{ .Values.clusterName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.clusterAutoscaler.namespace }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.clusterAutoscaler.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}