{{- if and (.Values.externalDns) (.Values.externalDns.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.externalDns.repoUrl }}
    path: {{ .Values.externalDns.path }}
    targetRevision: {{ .Values.externalDns.targetRevision }}
    helm:
      values: |
        {{- toYaml .Values.externalDns.values | nindent 8 }}
      parameters:
      - name: aws.region
        value: {{ .Values.region }}
      - name: serviceAccount.name
        value: {{ .Values.externalDns.serviceAccountName }}
      - name: zoneIdFilters[0]
        value: {{ .Values.externalDns.zoneIdFilter }}
      - name: interval
        value: {{ .Values.externalDns.interval }}
      - name: aws.credentials.accessKey	
        value: {{ .Values.externalDns.accessKey }}
      - name: aws.credentials.secretKey
        value: {{ .Values.externalDns.secretKey }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.externalDns.namespace }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.externalDns.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}