region: us-east-1
clusterName: ""

externalDns:
  enable: true
  repoUrl: https://github.com/bitnami/charts/
  path: bitnami/external-dns
  targetRevision: main
  namespace: platform
  createNamespace: false
  serviceAccountName: ""
  zoneIdFilter: ""
  interval: "30m"
  accessKey: ""
  secretKey: ""
  values: {}

clusterAutoscaler:
  enable: true
  repoUrl: https://github.com/kubernetes/autoscaler
  path: charts/cluster-autoscaler
  targetRevision: cluster-autoscaler-chart-9.21.1
  namespace: platform
  createNamespace: false
  serviceAccountName: "cluster-autoscaler-sa"
  values:
    expander: "least-waste"
    skip-nodes-with-system-pods: false
    skip-nodes-with-local-storage: false
    balance-similar-node-groups: false
    aws-use-static-instance-list: true

ingressNginx:
  enable: true
  repoUrl: https://github.com/kubernetes/ingress-nginx
  path: charts/ingress-nginx
  targetRevision: controller-v1.8.1
  namespace: platform
  createNamespace: false
  values:
    controller:
      service:
        external:
          enabled: false
        internal:
          enabled: true     
      ingressClassResource:
        default: true
